//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticMobileApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogisticMobileApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активный маршрут.
        /// </summary>
        public static string Active_Route_Label {
            get {
                return ResourceManager.GetString("Active_Route_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логистика мусора.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер автомобиля.
        /// </summary>
        public static string CarNumberPlaceholder {
            get {
                return ResourceManager.GetString("CarNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите код регистрации.
        /// </summary>
        public static string CodePlaceholder {
            get {
                return ResourceManager.GetString("CodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль.
        /// </summary>
        public static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий.
        /// </summary>
        public static string ConfirmRoute_CommentPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmRoute_CommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить сбор.
        /// </summary>
        public static string ConfirmRoute_ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmRoute_ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контейнеров:.
        /// </summary>
        public static string ConfirmRoute_ContainersLabel {
            get {
                return ResourceManager.GetString("ConfirmRoute_ContainersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить маршрут.
        /// </summary>
        public static string ConfirmRoute_FinishRouteButton {
            get {
                return ResourceManager.GetString("ConfirmRoute_FinishRouteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В сборе отказано.
        /// </summary>
        public static string ConfirmRoute_RejectButton {
            get {
                return ResourceManager.GetString("ConfirmRoute_RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string ConfirmRoute_SendComment {
            get {
                return ResourceManager.GetString("ConfirmRoute_SendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение точек.
        /// </summary>
        public static string ConfirmRoute_Title {
            get {
                return ResourceManager.GetString("ConfirmRoute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        public static string ContinueButtonText {
            get {
                return ResourceManager.GetString("ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В данный момент маршрута нет. Обратитесь к логисту..
        /// </summary>
        public static string Dashboard_NoRouteMessage {
            get {
                return ResourceManager.GetString("Dashboard_NoRouteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочая панель.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние.
        /// </summary>
        public static string Distance_Label {
            get {
                return ResourceManager.GetString("Distance_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Водитель.
        /// </summary>
        public static string Driver_Label {
            get {
                return ResourceManager.GetString("Driver_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активен.
        /// </summary>
        public static string DriverActiveLabel {
            get {
                return ResourceManager.GetString("DriverActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неактивен.
        /// </summary>
        public static string DriverInactiveLabel {
            get {
                return ResourceManager.GetString("DriverInactiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уже есть аккаунт? Войти.
        /// </summary>
        public static string GoToLoginLink {
            get {
                return ResourceManager.GetString("GoToLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет аккаунта? Зарегистрируйтесь.
        /// </summary>
        public static string GoToRegisterLink {
            get {
                return ResourceManager.GetString("GoToRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на км.
        /// </summary>
        public static string KilometersLabel {
            get {
                return ResourceManager.GetString("KilometersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Language_Cancel {
            get {
                return ResourceManager.GetString("Language_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык.
        /// </summary>
        public static string Language_PromptTitle {
            get {
                return ResourceManager.GetString("Language_PromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить активацию устройства.
        /// </summary>
        public static string Login_AutoLoginFailed {
            get {
                return ResourceManager.GetString("Login_AutoLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка входа....
        /// </summary>
        public static string Login_Checking {
            get {
                return ResourceManager.GetString("Login_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется активация.
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет соединения с сервером.
        /// </summary>
        public static string Login_NetworkError {
            get {
                return ResourceManager.GetString("Login_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автовход выполнен.
        /// </summary>
        public static string Login_Success {
            get {
                return ResourceManager.GetString("Login_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите выйти?.
        /// </summary>
        public static string Logout_ConfirmMessage {
            get {
                return ResourceManager.GetString("Logout_ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string Logout_No {
            get {
                return ResourceManager.GetString("Logout_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход из приложения.
        /// </summary>
        public static string Logout_Title {
            get {
                return ResourceManager.GetString("Logout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Logout_Yes {
            get {
                return ResourceManager.GetString("Logout_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Map_Back {
            get {
                return ResourceManager.GetString("Map_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К маршруту.
        /// </summary>
        public static string Map_CenterRoute {
            get {
                return ResourceManager.GetString("Map_CenterRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить.
        /// </summary>
        public static string Map_FinishRoute {
            get {
                return ResourceManager.GetString("Map_FinishRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моё место.
        /// </summary>
        public static string Map_MyLocation {
            get {
                return ResourceManager.GetString("Map_MyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я.
        /// </summary>
        public static string Map_MyLocationMarker {
            get {
                return ResourceManager.GetString("Map_MyLocationMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навигация.
        /// </summary>
        public static string Map_Navigate {
            get {
                return ResourceManager.GetString("Map_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о маршруте.
        /// </summary>
        public static string Map_RouteInfo {
            get {
                return ResourceManager.GetString("Map_RouteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ↓ Кликни, чтобы скрыть.
        /// </summary>
        public static string Map_TapToCollapse {
            get {
                return ResourceManager.GetString("Map_TapToCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ↑ Кликни, чтобы показать точки.
        /// </summary>
        public static string Map_TapToExpand {
            get {
                return ResourceManager.GetString("Map_TapToExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта маршрута.
        /// </summary>
        public static string Map_Title {
            get {
                return ResourceManager.GetString("Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мин.
        /// </summary>
        public static string MinutesLabel {
            get {
                return ResourceManager.GetString("MinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активация не удалась.
        /// </summary>
        public static string Register_Failed {
            get {
                return ResourceManager.GetString("Register_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройство успешно активировано.
        /// </summary>
        public static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Построить маршрут.
        /// </summary>
        public static string Route_Button {
            get {
                return ResourceManager.GetString("Route_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Построить маршрут.
        /// </summary>
        public static string Routes_BuildButton {
            get {
                return ResourceManager.GetString("Routes_BuildButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контейнеров:.
        /// </summary>
        public static string Routes_ContainersLabel {
            get {
                return ResourceManager.GetString("Routes_ContainersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор точек.
        /// </summary>
        public static string Routes_Title {
            get {
                return ResourceManager.GetString("Routes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить пароль.
        /// </summary>
        public static string Settings_ChangePassword {
            get {
                return ResourceManager.GetString("Settings_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переключить тему.
        /// </summary>
        public static string Settings_ChangeTheme {
            get {
                return ResourceManager.GetString("Settings_ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык.
        /// </summary>
        public static string Settings_ChooseLanguage {
            get {
                return ResourceManager.GetString("Settings_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль.
        /// </summary>
        public static string Settings_ConfirmPassword {
            get {
                return ResourceManager.GetString("Settings_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль.
        /// </summary>
        public static string Settings_NewPassword {
            get {
                return ResourceManager.GetString("Settings_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль успешно изменён (демо).
        /// </summary>
        public static string Settings_PasswordConfirmed {
            get {
                return ResourceManager.GetString("Settings_PasswordConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают.
        /// </summary>
        public static string Settings_PasswordMismatch {
            get {
                return ResourceManager.GetString("Settings_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать маршрут.
        /// </summary>
        public static string ShowRouteLabel {
            get {
                return ResourceManager.GetString("ShowRouteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать.
        /// </summary>
        public static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маршрут начат!.
        /// </summary>
        public static string StartRouteToast {
            get {
                return ResourceManager.GetString("StartRouteToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика.
        /// </summary>
        public static string Statistics_Button {
            get {
                return ResourceManager.GetString("Statistics_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тёмная тема.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлая тема.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время в пути.
        /// </summary>
        public static string TravelTimeLabel {
            get {
                return ResourceManager.GetString("TravelTimeLabel", resourceCulture);
            }
        }
    }
}
